"""DEPOT (DrugRec): Motif-based drug recommendation.

Architecture must exactly match saved checkpoints from medrec_pipeline training.
Requires preprocessed PKL files: drug_smile, smile_sub_b, smile_sub_degree_b,
smile_sub_recency_b (generated by medrec_pipeline preprocessing).
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence


def _get_indices(matrix):
    nz   = torch.nonzero(matrix, as_tuple=False)[:, 1]
    lens = list(torch.sum(matrix, 1).long().cpu().numpy())
    return nz, lens


def _get_nonzero(mat):
    return torch.masked_select(mat, mat != 0)


class SubGraphNetwork(nn.Module):
    def __init__(self, sub_embed, emb_dim, smile_num):
        super().__init__()
        self.sub_emb     = sub_embed
        self.smile_emb   = nn.Embedding(smile_num, emb_dim)
        self.recency_emb = nn.Embedding(30, emb_dim)
        self.degree_emb  = nn.Embedding(30, emb_dim)
        self.dropout     = nn.Dropout(0.7)
        self.ff          = nn.Linear(emb_dim, emb_dim, bias=False)
        enc_layer = nn.TransformerEncoderLayer(
            d_model=emb_dim, nhead=2, dim_feedforward=emb_dim,
            dropout=0.2, batch_first=True)
        self.transformer = nn.TransformerEncoder(enc_layer, num_layers=2)
        nn.init.xavier_uniform_(self.smile_emb.weight)
        nn.init.xavier_uniform_(self.recency_emb.weight)
        nn.init.xavier_uniform_(self.degree_emb.weight)

    def _get_emb(self, smile_sub_matrix, recency_matrix, degree_matrix):
        sub_ids, lens = _get_indices(smile_sub_matrix)
        seqs   = [v for v in torch.split(sub_ids, lens)]
        padded = pad_sequence(seqs, batch_first=True, padding_value=0).long()
        sub_e  = self.sub_emb(padded)
        mask   = (padded == 0).bool()

        rec = _get_nonzero(recency_matrix)
        rec = [torch.sort(v)[1] for v in torch.split(rec, lens)]
        rec = pad_sequence(rec, batch_first=True, padding_value=0).long()
        rec_e = self.recency_emb(rec)

        deg = _get_nonzero(degree_matrix)
        deg = [torch.sort(v)[1] for v in torch.split(deg, lens)]
        deg = pad_sequence(deg, batch_first=True, padding_value=0).long()
        deg_e = self.degree_emb(deg)

        emb = self.dropout(self.ff(rec_e + deg_e)) + sub_e
        return emb, mask

    def forward(self, inputs, query=None):
        smile_sub, recency, degree, drug_smile = inputs
        emb, mask = self._get_emb(smile_sub, recency, degree)
        x   = self.transformer(emb, src_key_padding_mask=mask)
        m   = (~mask).float().unsqueeze(-1)
        rep = (x * m).sum(1) / m.sum(1).clamp(min=1)
        rep = rep + self.smile_emb.weight
        if query is not None:
            attn     = F.softmax(torch.matmul(query, rep.t()), -1)
            drug_rep = attn.matmul(rep)
            return F.normalize(drug_rep, p=2, dim=1)
        return rep


class DrugRecNet(nn.Module):
    def __init__(self, voc_size, emb_dim, drug_smile, smile_sub,
                 ddi_matrix, structure_matrix, device):
        super().__init__()
        self.device     = device
        self.emb_dim    = emb_dim
        self.voc_size   = voc_size
        self.drug_smile = drug_smile
        self.smile_sub  = smile_sub
        self.drug_sub   = (drug_smile @ smile_sub).bool().float()
        self.sub_num    = smile_sub.shape[1]

        self.diag_emb = nn.Embedding(voc_size[0], emb_dim)
        self.proc_emb = nn.Embedding(voc_size[1], emb_dim)
        self.dropout  = nn.Dropout(0.7)
        self.diag_enc = nn.GRU(emb_dim, emb_dim, batch_first=True)
        self.proc_enc = nn.GRU(emb_dim, emb_dim, batch_first=True)
        self.query    = nn.Sequential(nn.ReLU(), nn.Linear(2 * emb_dim, emb_dim))

        self.sub_embed = nn.Embedding(self.sub_num, emb_dim)
        self.graph_net = SubGraphNetwork(
            self.sub_embed, emb_dim, drug_smile.shape[1]).to(device)
        self.stru = structure_matrix

        self.drug_output = nn.Linear(voc_size[2], voc_size[2])
        self.drug_norm   = nn.LayerNorm(voc_size[2])
        self.drug_emb_id = nn.Embedding(drug_smile.shape[0], emb_dim)
        self.ddi_matrix  = ddi_matrix

        self.W_mu     = nn.Linear(emb_dim, emb_dim)
        self.W_s      = nn.Linear(emb_dim, emb_dim)
        self.his_attn = nn.Linear(emb_dim, 1)

        def _iw(m):
            if isinstance(m, (nn.Linear, nn.Embedding)):
                nn.init.xavier_uniform_(m.weight)
        self.apply(_iw)

    def forward(self, input_seq):
        diag_s, proc_s = [], []
        for adm in input_seq:
            d = self.dropout(self.diag_emb(
                torch.LongTensor(adm[0]).unsqueeze(0).to(self.device))).sum(1).unsqueeze(0)
            p = self.dropout(self.proc_emb(
                torch.LongTensor(adm[1]).unsqueeze(0).to(self.device))).sum(1).unsqueeze(0)
            diag_s.append(d); proc_s.append(p)
        diag_s = torch.cat(diag_s, 1); proc_s = torch.cat(proc_s, 1)
        o1, _ = self.diag_enc(diag_s); o2, _ = self.proc_enc(proc_s)
        h = self.query(torch.cat([o1, o2], -1).squeeze(0))
        q = h[-1:]   # (1, emb)

        drug_emb = self.graph_net(
            [self.smile_sub, self.stru[0], self.stru[1], self.drug_smile],
            self.drug_emb_id.weight)
        drug_emb = drug_emb + self.drug_emb_id.weight

        match = torch.sigmoid(q.mm(drug_emb.t()))
        match = self.drug_norm(match + self.drug_output(match))

        neg = torch.sigmoid(match)
        neg = neg.t() * neg
        ddi = 0.0005 * neg.mul(self.ddi_matrix).sum()
        return match, ddi
